# Generated by Django 5.1.4 on 2025-01-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='member',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
