# Generated by Django 5.0 on 2024-04-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('physical_address', models.TextField()),
                ('place_of_domicile', models.CharField(max_length=100)),
                ('current_place_of_residency', models.CharField(max_length=100)),
                ('year_of_study', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('ministry', models.CharField(max_length=100)),
                ('current_place_of_worship', models.CharField(max_length=100)),
                ('previous_place_of_worship', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_images/')),
                ('sex', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creditor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ManyToManyField(to='database.course')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Lecture Notes', 'Lecture Notes'), ('Assignments', 'Assignments'), ('Reference Materials', 'Reference Materials'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='materials/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.module')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.contribution')),
            ],
        ),
    ]
