# Generated by Django 4.2.4 on 2024-09-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='status',
            new_name='description',
        ),
    ]
