# Generated by Django 4.2.4 on 2024-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_status_contribution_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
