# Generated by Django 5.1.4 on 2024-12-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_contribution_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voucher',
            new_name='Expenditure',
        ),
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Revenue',
        ),
    ]
