# Generated by Django 5.1.4 on 2025-01-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_voucher_expenditure_rename_receipt_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=20, unique=True)),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('Approved_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('recorder_name', models.CharField(max_length=100)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='database.contribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='database.member')),
            ],
        ),
    ]
