# Generated by Django 5.1.4 on 2025-01-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_voucher_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_code',
            field=models.CharField(max_length=20),
        ),
    ]
