# Generated by Django 5.1.4 on 2025-01-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_receipt_receipt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(max_length=20),
        ),
    ]
